Add a checker to ensure that the currently installed version of Plesk is available on autoinstall.plesk.com
plesk/dist-upgrader pull request #28
Opened 2024-04-15 05:54 UTC by SandakovMM

2024-04-16 03:01 UTC, kpushkaryov requested changes

2024-04-16 07:10 UTC, SandakovMM commented on pleskdistup/common/src/version.py
> +class PleskVersion():
Let's add some additional commentary

2024-04-17 04:45 UTC, kpushkaryov requested changes

2024-04-17 04:45 UTC, kpushkaryov commented on pleskdistup/common/src/version.py
> +class PleskVersion():
I mean, you don't need `()`.

2024-04-17 04:45 UTC, kpushkaryov commented on pleskdistup/common/src/version.py
> +        return (self.major, self.minor, self.patch, self.hotfix) < (other.major, other.minor, other.patch, other.hotfix)
Repeating `(major, minor, ...)` seems excessive, please create a private method converting the version to a tuple.

2024-04-17 04:45 UTC, kpushkaryov commented on pleskdistup/common/src/plesk.py
> +# http://autoinstall.plesk.com/products.inf3 is a xml file with available products,
a xml -> an xml

2024-04-17 04:45 UTC, kpushkaryov commented on pleskdistup/common/src/plesk.py
> +# including all versions of plesk.
plesk -> Plesk

2024-04-17 05:36 UTC, kpushkaryov approved these changes
Please rebase before merge.

2024-04-17 06:40 UTC, merged